# Example Site settings

#google_analytics: UA-NNNNNNNN-N

header_pages:
  - index.html

name: lianaovn

author:
  name: liandd
  url: http://liandd.github.io

logourl: /assets/images/masthead.png"

footer: "La mayoría de las personas sólo juzgan a los hombres por el crédito de que gozan o por su buena suerte. La Rochefoucauld, F. (1665). Reflexiones; Sentencias y Máximas Morales."

#style: light # dark (default) or light
#listen_for_clients_preferred_style: true # true or false (default)

plugins:
  - jekyll-seo-tag
